mixed-port: 7897
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:39798
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
proxies:
  - name: 🇭🇰|香港-中转 01
    type: trojan
    server: z1.ioioioioioio.com
    port: 33449
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.hk2.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇭🇰|香港-中转 02
    type: trojan
    server: z2.ioioioioioio.com
    port: 18605
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.hk5.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇭🇰|香港-直连
    type: trojan
    server: dd.ioioioioioio.com
    port: 40514
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: d.hkq1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇭🇰|香港家宽-中转
    type: trojan
    server: z1.ioioioioioio.com
    port: 26173
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.hk7.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇭🇰|香港家宽-直连
    type: trojan
    server: dd.ioioioioioio.com
    port: 12588
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: d.hkh1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇭🇰|香港-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20100
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇭🇰|香港-IEPL 03
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20055
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇭🇰|香港家宽-IEPL
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20037
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇸🇬|新加坡-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20067
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: SG.catxstar.com
    skip-cert-verify: true
  - name: 🇸🇬|新加坡-IEPL 02
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20084
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: SG.catxstar.com
    skip-cert-verify: true
  - name: 🇸🇬|新加坡-IEPL 03
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20040
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: SG.catxstar.com
    skip-cert-verify: true
  - name: 🇸🇬|新加坡-直连
    type: trojan
    server: dd.ioioioioioio.com
    port: 41909
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: d.sgq1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇸🇬|新加坡-中转 01
    type: trojan
    server: z1.ioioioioioio.com
    port: 12300
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.sg1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇸🇬|新加坡-中转 02
    type: trojan
    server: z1.ioioioioioio.com
    port: 16499
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.sg4.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20021
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: TW.catxstar.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾-IEPL 02
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20082
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: TW.catxstar.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾-IEPL 03
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20131
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: TW.catxstar.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾家宽-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20108
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: tw.catxstar.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾家宽-IEPL 02
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20090
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: tw.catxstar.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾-直连
    type: trojan
    server: dd.ioioioioioio.com
    port: 19135
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: d.twq1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾-中转 01
    type: trojan
    server: z1.ioioioioioio.com
    port: 52641
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.tw1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇹🇼|台湾-中转 02
    type: trojan
    server: z2.ioioioioioio.com
    port: 52752
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.tw1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇯🇵|日本-中转 01
    type: trojan
    server: z1.ioioioioioio.com
    port: 28655
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.JP5.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇯🇵|日本-中转 02
    type: trojan
    server: z2.ioioioioioio.com
    port: 13608
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.JP6.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇯🇵|日本-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20005
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇯🇵|日本-IEPL 02
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20105
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇯🇵|日本原生-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20099
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇯🇵|日本原生-IEPL 02
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20099
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: hk.catxstar.com
    skip-cert-verify: true
  - name: 🇯🇵|日本原生-中转 01
    type: trojan
    server: z1.ioioioioioio.com
    port: 15990
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.JP9.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇯🇵|日本原生-中转 02
    type: trojan
    server: z2.ioioioioioio.com
    port: 34176
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.JP10.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇯🇵|日本原生-直连
    type: trojan
    server: dd.ioioioioioio.com
    port: 44555
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: d.jpq1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇺🇸|美国-IEPL 01
    type: trojan
    server: iepl-q.ioioioioioio.com
    port: 20094
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: US.catxstar.com
    skip-cert-verify: true
  - name: 🇺🇸|美国-IEPL 02
    type: trojan
    server: iepl-t.ioioioioioio.com
    port: 20093
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: US.catxstar.com
    skip-cert-verify: true
  - name: 🇺🇸|美国-直连
    type: trojan
    server: dd.ioioioioioio.com
    port: 41613
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: d.usq1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇺🇸|美国-中转 01
    type: trojan
    server: z1.ioioioioioio.com
    port: 26947
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.US1.cat.bilibili.com
    skip-cert-verify: true
  - name: 🇺🇸|美国-中转 02
    type: trojan
    server: z2.ioioioioioio.com
    port: 18479
    password: 966e4f47-ff12-477d-8aa1-71bc5320ca53
    udp: true
    sni: r.US2.cat.bilibili.com
    skip-cert-verify: true
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动节点
      - 香港自动
      - 日本自动
      - 🇭🇰|香港-中转 01
      - 🇭🇰|香港-中转 02
      - 🇭🇰|香港-直连
      - 🇭🇰|香港家宽-中转
      - 🇭🇰|香港家宽-直连
      - 🇭🇰|香港-IEPL 01
      - 🇭🇰|香港-IEPL 03
      - 🇭🇰|香港家宽-IEPL
      - 🇸🇬|新加坡-IEPL 01
      - 🇸🇬|新加坡-IEPL 02
      - 🇸🇬|新加坡-IEPL 03
      - 🇸🇬|新加坡-直连
      - 🇸🇬|新加坡-中转 01
      - 🇸🇬|新加坡-中转 02
      - 🇹🇼|台湾-IEPL 01
      - 🇹🇼|台湾-IEPL 02
      - 🇹🇼|台湾-IEPL 03
      - 🇹🇼|台湾家宽-IEPL 01
      - 🇹🇼|台湾家宽-IEPL 02
      - 🇹🇼|台湾-直连
      - 🇹🇼|台湾-中转 01
      - 🇹🇼|台湾-中转 02
      - 🇯🇵|日本-中转 01
      - 🇯🇵|日本-中转 02
      - 🇯🇵|日本-IEPL 01
      - 🇯🇵|日本-IEPL 02
      - 🇯🇵|日本原生-IEPL 01
      - 🇯🇵|日本原生-IEPL 02
      - 🇯🇵|日本原生-中转 01
      - 🇯🇵|日本原生-中转 02
      - 🇯🇵|日本原生-直连
      - 🇺🇸|美国-IEPL 01
      - 🇺🇸|美国-IEPL 02
      - 🇺🇸|美国-直连
      - 🇺🇸|美国-中转 01
      - 🇺🇸|美国-中转 02
  - name: 自动节点
    type: url-test
    proxies:
      - 🇭🇰|香港-中转 01
      - 🇭🇰|香港-中转 02
      - 🇭🇰|香港-直连
      - 🇭🇰|香港家宽-中转
      - 🇭🇰|香港家宽-直连
      - 🇭🇰|香港-IEPL 01
      - 🇭🇰|香港-IEPL 03
      - 🇭🇰|香港家宽-IEPL
      - 🇸🇬|新加坡-IEPL 01
      - 🇸🇬|新加坡-IEPL 02
      - 🇸🇬|新加坡-IEPL 03
      - 🇸🇬|新加坡-直连
      - 🇸🇬|新加坡-中转 01
      - 🇸🇬|新加坡-中转 02
      - 🇹🇼|台湾-IEPL 01
      - 🇹🇼|台湾-IEPL 02
      - 🇹🇼|台湾-IEPL 03
      - 🇹🇼|台湾家宽-IEPL 01
      - 🇹🇼|台湾家宽-IEPL 02
      - 🇹🇼|台湾-直连
      - 🇹🇼|台湾-中转 01
      - 🇹🇼|台湾-中转 02
      - 🇯🇵|日本-中转 01
      - 🇯🇵|日本-中转 02
      - 🇯🇵|日本-IEPL 01
      - 🇯🇵|日本-IEPL 02
      - 🇯🇵|日本原生-IEPL 01
      - 🇯🇵|日本原生-IEPL 02
      - 🇯🇵|日本原生-中转 01
      - 🇯🇵|日本原生-中转 02
      - 🇯🇵|日本原生-直连
      - 🇺🇸|美国-IEPL 01
      - 🇺🇸|美国-IEPL 02
      - 🇺🇸|美国-直连
      - 🇺🇸|美国-中转 01
      - 🇺🇸|美国-中转 02
    url: http://cp.cloudflare.com/generate_204
    interval: 3600
    tolerance: 50
    lazy: true
  - name: 香港自动
    type: url-test
    proxies:
      - 🇭🇰|香港-中转 01
      - 🇭🇰|香港-中转 02
      - 🇭🇰|香港-直连
      - 🇭🇰|香港家宽-中转
      - 🇭🇰|香港家宽-直连
      - 🇭🇰|香港-IEPL 01
      - 🇭🇰|香港-IEPL 03
      - 🇭🇰|香港家宽-IEPL
    url: http://cp.cloudflare.com/generate_204
    interval: 3600
    tolerance: 50
    lazy: true
  - name: 日本自动
    type: url-test
    proxies:
      - 🇯🇵|日本-中转 01
      - 🇯🇵|日本-中转 02
      - 🇯🇵|日本-IEPL 01
      - 🇯🇵|日本-IEPL 02
      - 🇯🇵|日本原生-IEPL 01
      - 🇯🇵|日本原生-IEPL 02
      - 🇯🇵|日本原生-中转 01
      - 🇯🇵|日本原生-中转 02
      - 🇯🇵|日本原生-直连
    url: http://cp.cloudflare.com/generate_204
    interval: 3600
    tolerance: 50
    lazy: true
rules:
  - DOMAIN,injections.adguard.org,DIRECT
  - DOMAIN,local.adguard.org,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - DOMAIN-KEYWORD,apple.com.akadns.net,DIRECT
  - DOMAIN-KEYWORD,icloud.com.akadns.net,DIRECT
  - DOMAIN-SUFFIX,aaplimg.com,DIRECT
  - DOMAIN-SUFFIX,apple.co,DIRECT
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
  - DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
  - DOMAIN-SUFFIX,appsto.re,DIRECT
  - DOMAIN-SUFFIX,cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,icloud-content.com,DIRECT
  - DOMAIN-SUFFIX,itunes.com,DIRECT
  - DOMAIN-SUFFIX,me.com,DIRECT
  - DOMAIN-SUFFIX,mzstatic.com,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,63.92.224.0/19,DIRECT
  - IP-CIDR,65.199.22.0/23,DIRECT
  - IP-CIDR,139.178.128.0/18,DIRECT
  - IP-CIDR,144.178.0.0/19,DIRECT
  - IP-CIDR,144.178.36.0/22,DIRECT
  - IP-CIDR,144.178.48.0/20,DIRECT
  - IP-CIDR,192.35.50.0/24,DIRECT
  - IP-CIDR,198.183.17.0/24,DIRECT
  - IP-CIDR,205.180.175.0/24,DIRECT
  - DOMAIN-SUFFIX,apple.comscoreresearch.com,DIRECT
  - DOMAIN-SUFFIX,apple.news,DIRECT
  - PROCESS-NAME,com.apple.geod,DIRECT
  - DOMAIN-SUFFIX,s.team,DIRECT
  - DOMAIN-SUFFIX,steampowered.com,DIRECT
  - DOMAIN-SUFFIX,steamcommunity.com,DIRECT
  - DOMAIN-SUFFIX,steamgames.com,DIRECT
  - DOMAIN-SUFFIX,steamusercontent.com,DIRECT
  - DOMAIN-SUFFIX,steamstatic.com,DIRECT
  - DOMAIN,csgo.wmsj.cn,DIRECT
  - DOMAIN,dl.steam.clngaa.com,DIRECT
  - DOMAIN,dl.steam.ksyna.com,DIRECT
  - DOMAIN,dota2.wmsj.cn,DIRECT
  - DOMAIN,st.dl.bscstorage.net,DIRECT
  - DOMAIN,st.dl.eccdnx.com,DIRECT
  - DOMAIN,st.dl.pinyuncloud.com,DIRECT
  - DOMAIN,steampipe.steamcontent.tnkjmec.com,DIRECT
  - DOMAIN,steampowered.com.8686c.com,DIRECT
  - DOMAIN,steamstatic.com.8686c.com,DIRECT
  - DOMAIN,wmsjsteam.com,DIRECT
  - DOMAIN,xz.pphimalayanrt.com,DIRECT
  - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
  - DOMAIN-SUFFIX,steamchina.com,DIRECT
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT
  - DOMAIN-SUFFIX,steamserver.net,DIRECT
  - DOMAIN-SUFFIX,steamusercontent.com,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT
  - DOMAIN-SUFFIX,openai.com,🇺🇸|美国-IEPL 02
  - DOMAIN-SUFFIX,chatgpt.com,🇺🇸|美国-IEPL 02
  - DOMAIN-SUFFIX,chatgpt-api.com,🇺🇸|美国-IEPL 02
  - DOMAIN-SUFFIX,oaistatic.com,🇺🇸|美国-IEPL 02
  - DOMAIN-SUFFIX,oaiusercontent.com,🇺🇸|美国-IEPL 02
  - GEOIP, CN, DIRECT
  - MATCH, 🇭🇰|香港-IEPL 01
script: null
rule-providers: null
enable-process: true
tun:
  enable: false
  stack: gvisor
  dns-hijack:
    - 0.0.0.0:53
  auto-route: true
  auto-detect-interface: true
